flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
  min_sdk_android: 21
